// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    JoseVerifyRequest,
    JoseVerifyResponse,
    Result,
} from '../models';

export interface JoseVerifyApiRequest {
    joseVerifyRequest?: JoseVerifyRequest;
}

/**
 * no description
 */
export class JoseObjectApi extends BaseAPI {

    /**
     * This API verifies a JOSE object. 
     * /api/jose/verify API
     */
    joseVerifyApi({ joseVerifyRequest }: JoseVerifyApiRequest): Observable<JoseVerifyResponse>
    joseVerifyApi({ joseVerifyRequest }: JoseVerifyApiRequest, opts?: OperationOpts): Observable<AjaxResponse<JoseVerifyResponse>>
    joseVerifyApi({ joseVerifyRequest }: JoseVerifyApiRequest, opts?: OperationOpts): Observable<JoseVerifyResponse | AjaxResponse<JoseVerifyResponse>> {

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
            ...(this.configuration.username != null && this.configuration.password != null ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` } : undefined),
        };

        return this.request<JoseVerifyResponse>({
            url: '/api/jose/verify',
            method: 'POST',
            headers,
            body: joseVerifyRequest,
        }, opts?.responseOpts);
    };

}
