// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.2.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    PushedAuthReqRequest,
    PushedAuthReqResponse,
    Result,
} from '../models';

export interface PushedAuthReqApiRequest {
    pushedAuthReqRequest: PushedAuthReqRequest;
}

/**
 * no description
 */
export class PushedAuthorizationEndpointApi extends BaseAPI {

    /**
     * This API creates a pushed request authorization. It authenticates the client and creates a authorization_uri to be returned by the authorization server. 
     * /api/pushed_auth_req API
     */
    pushedAuthReqApi({ pushedAuthReqRequest }: PushedAuthReqApiRequest): Observable<PushedAuthReqResponse>
    pushedAuthReqApi({ pushedAuthReqRequest }: PushedAuthReqApiRequest, opts?: OperationOpts): Observable<AjaxResponse<PushedAuthReqResponse>>
    pushedAuthReqApi({ pushedAuthReqRequest }: PushedAuthReqApiRequest, opts?: OperationOpts): Observable<PushedAuthReqResponse | AjaxResponse<PushedAuthReqResponse>> {
        throwIfNullOrUndefined(pushedAuthReqRequest, 'pushedAuthReqRequest', 'pushedAuthReqApi');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
            ...(this.configuration.username != null && this.configuration.password != null ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` } : undefined),
        };

        return this.request<PushedAuthReqResponse>({
            url: '/api/pushed_auth_req',
            method: 'POST',
            headers,
            body: pushedAuthReqRequest,
        }, opts?.responseOpts);
    };

}
