// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.2.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    GrantType,
    Property,
} from './';

/**
 * @export
 * @interface AccessToken
 */
export interface AccessToken {
    /**
     * The hash of the access token.
     * @type {string}
     * @memberof AccessToken
     */
    accessTokenHash?: string;
    /**
     * The timestamp at which the access token will expire.
     * @type {number}
     * @memberof AccessToken
     */
    accessTokenExpiresAt?: number;
    /**
     * The hash of the refresh token.
     * @type {string}
     * @memberof AccessToken
     */
    refreshTokenHash?: string;
    /**
     * The timestamp at which the refresh token will expire.
     * @type {number}
     * @memberof AccessToken
     */
    refreshTokenExpiresAt?: number;
    /**
     * The timestamp at which the access token was first created. 
     * @type {number}
     * @memberof AccessToken
     */
    createdAt?: number;
    /**
     * The timestamp at which the access token was last refreshed using the refresh token. 
     * @type {number}
     * @memberof AccessToken
     */
    lastRefreshedAt?: number;
    /**
     * The ID of the client associated with the access token. 
     * @type {number}
     * @memberof AccessToken
     */
    clientId?: number;
    /**
     * The subject (= unique user ID) associated with the access token. 
     * @type {string}
     * @memberof AccessToken
     */
    subject?: string;
    /**
     * @type {GrantType}
     * @memberof AccessToken
     */
    grantType?: GrantType;
    /**
     * The scopes associated with the access token. 
     * @type {Array<string>}
     * @memberof AccessToken
     */
    scopes?: Array<string>;
    /**
     * The properties associated with the access token. 
     * @type {Array<Property>}
     * @memberof AccessToken
     */
    properties?: Array<Property>;
}
