// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.2.30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface BackchannelAuthenticationRequest
 */
export interface BackchannelAuthenticationRequest {
    /**
     * Parameters of a backchannel authentication request which are the request parameters that the backchannel authentication endpoint of the OpenID provider implementation received from the client application.  The value of `parameters` is the entire entity body (which is formatted in `application/x-www-form-urlencoded`) of the request from the client application. 
     * @type {string}
     * @memberof BackchannelAuthenticationRequest
     */
    parameters: string;
    /**
     * The client ID extracted from Authorization header of the backchannel authentication request from the client application.  If the backchannel authentication endpoint of the OpenID provider implementation supports Basic Authentication as a means of client authentication, and the request from the client application contained its client ID in Authorization header, the value should be extracted and set to this parameter. 
     * @type {string}
     * @memberof BackchannelAuthenticationRequest
     */
    clientId?: string;
    /**
     * The client secret extracted from Authorization header of the backchannel authentication request from the client application.  If the backchannel authentication endpoint of the OpenID provider implementation supports Basic Authentication as a means of client authentication, and the request from the client application contained its client secret in Authorization header, the value should be extracted and set to this parameter. 
     * @type {string}
     * @memberof BackchannelAuthenticationRequest
     */
    clientSecret?: string;
    /**
     * The client certification used in the TLS connection between the client application and the backchannel authentication endpoint of the OpenID provider. 
     * @type {string}
     * @memberof BackchannelAuthenticationRequest
     */
    clientCertificate?: string;
    /**
     * The client certificate path presented by the client during client authentication. Each element is a string in PEM format.
     * @type {string}
     * @memberof BackchannelAuthenticationRequest
     */
    clientCertificatePath?: string;
}
