// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.2.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface BackchannelAuthenticationIssueRequest
 */
export interface BackchannelAuthenticationIssueRequest {
    /**
     * The ticket issued from Authlete\'s `/backchannel/authentication` API.
     * @type {string}
     * @memberof BackchannelAuthenticationIssueRequest
     */
    ticket: string;
}
