// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.2.30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    Client,
} from './';

/**
 * @export
 * @interface ClientRegistrationGetResponse
 */
export interface ClientRegistrationGetResponse {
    /**
     * The code which represents the result of the API call.
     * @type {string}
     * @memberof ClientRegistrationGetResponse
     */
    resultCode?: string;
    /**
     * A short message which explains the result of the API call.
     * @type {string}
     * @memberof ClientRegistrationGetResponse
     */
    resultMessage?: string;
    /**
     * The next action that the authorization server implementation should take. 
     * @type {string}
     * @memberof ClientRegistrationGetResponse
     */
    action?: ClientRegistrationGetResponseActionEnum;
    /**
     * The content that the authorization server implementation is to return to the client application. Its format varies depending on the value of `action` parameter. 
     * @type {string}
     * @memberof ClientRegistrationGetResponse
     */
    responseContent?: string;
    /**
     * @type {Client}
     * @memberof ClientRegistrationGetResponse
     */
    client?: Client;
}

/**
 * @export
 * @enum {string}
 */
export enum ClientRegistrationGetResponseActionEnum {
    InternalServerError = 'INTERNAL_SERVER_ERROR',
    BadRequest = 'BAD_REQUEST',
    Ok = 'OK',
    Unauthorized = 'UNAUTHORIZED'
}

