// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.2.30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ClientGrantedScopesGetResponse
 */
export interface ClientGrantedScopesGetResponse {
    /**
     * The code which represents the result of the API call.
     * @type {string}
     * @memberof ClientGrantedScopesGetResponse
     */
    resultCode?: string;
    /**
     * A short message which explains the result of the API call.
     * @type {string}
     * @memberof ClientGrantedScopesGetResponse
     */
    resultMessage?: string;
    /**
     * The API key of the service.
     * @type {number}
     * @memberof ClientGrantedScopesGetResponse
     */
    serviceApiKey?: number;
    /**
     * The client ID.
     * @type {number}
     * @memberof ClientGrantedScopesGetResponse
     */
    clientId?: number;
    /**
     * The subject (= unique identifier) of the user who has granted authorization to the client.
     * @type {string}
     * @memberof ClientGrantedScopesGetResponse
     */
    subject?: string;
    /**
     * The scopes granted to the client application by the last authorization process by the user (who is identified by the subject). `null` means that there is no record about granted scopes. An empty array means that there exists a record about granted scopes but no scope has been granted to the client application. If the returned array holds some elements, they are the scopes granted to the client application by the last authorization process. 
     * @type {Array<string>}
     * @memberof ClientGrantedScopesGetResponse
     */
    latestGrantedScopes?: Array<string>;
    /**
     * The scopes granted to the client application by all the past authorization processes. Note that revoked scopes are not included. 
     * @type {Array<string>}
     * @memberof ClientGrantedScopesGetResponse
     */
    mergedGrantedScopes?: Array<string>;
    /**
     * The timestamp in milliseconds since Unix epoch at which this record was modified.
     * @type {number}
     * @memberof ClientGrantedScopesGetResponse
     */
    modifiedAt?: number;
}
