// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.2.30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ClientExtension
 */
export interface ClientExtension {
    /**
     * The set of scopes that the client application is allowed to request. This paramter will be one of the following.    - `null`   - an empty set   - a set with at least one element  When the value of this parameter is `null`, it means that the set of scopes that the client application is allowed to request is the set of the scopes that the service supports. When the value of this parameter is an empty set, it means that the client application is not allowed to request any scopes. When the value of this parameter is a set with at least one element, it means that the set is the set of scopes that the client application is allowed to request. 
     * @type {Array<string>}
     * @memberof ClientExtension
     */
    requestableScopes?: Array<string>;
    /**
     * The flag to indicate whether \"Requestable Scopes per Client\" is enabled or not. If `true`, you can define the set of scopes which this client application can request. If `false`, this client application can request any scope which is supported by the authorization server. 
     * @type {boolean}
     * @memberof ClientExtension
     */
    requestableScopesEnabled?: boolean;
    /**
     * The value of the duration of access tokens per client in seconds. In normal cases, the value of the service\'s `accessTokenDuration` property is used as the duration of access tokens issued by the service. However, if this `accessTokenDuration` property holds a non-zero positive number and its value is less than the duration configured by the service, the value is used as the duration of access tokens issued to the client application.  Note that the duration of access tokens can be controlled by the scope attribute `access_token.duration`, too. Authlete chooses the minimum value among the candidates. 
     * @type {number}
     * @memberof ClientExtension
     */
    accessTokenDuration?: number;
    /**
     * The value of the duration of refresh tokens per client in seconds. In normal cases, the value of the service\'s `refreshTokenDuration` property is used as the duration of refresh tokens issued by the service. However, if this `refreshTokenDuration` property holds a non-zero positive number and its value is less than the duration configured by the service, the value is used as the duration of refresh tokens issued to the client application.  Note that the duration of refresh tokens can be controlled by the scope attribute `refresh_token.duration`, too. Authlete chooses the minimum value among the candidates.
     * @type {number}
     * @memberof ClientExtension
     */
    refreshTokenDuration?: number;
}
