// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ClientExtensionRequestableScopesUpdateRequest
 */
export interface ClientExtensionRequestableScopesUpdateRequest {
    /**
     * The set of scopes that the client application is allowed to request. This parameter will be one of the following. Details are described in the description.  - null - an empty set - a set with at least one element  If this parameter contains scopes that the service does not support, those scopes are just ignored. Also, if this parameter is `null` or is not included in the request, it is equivalent to calling `/client/extension/requestable_scopes/delete` API.
     * @type {Array<string>}
     * @memberof ClientExtensionRequestableScopesUpdateRequest
     */
    requestableScopes?: Array<string>;
}
