// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ClientFlagUpdateRequest
 */
export interface ClientFlagUpdateRequest {
    /**
     * The flag value to be set 
     * @type {boolean}
     * @memberof ClientFlagUpdateRequest
     */
    clientLocked: boolean;
}
