// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.2.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ClientRegistrationUpdateRequest
 */
export interface ClientRegistrationUpdateRequest {
    /**
     * Client ID. 
     * @type {string}
     * @memberof ClientRegistrationUpdateRequest
     */
    clientId: string;
    /**
     * Client registration access token. 
     * @type {string}
     * @memberof ClientRegistrationUpdateRequest
     */
    token: string;
    /**
     * Client metadata in JSON format that complies with [RFC 7591](https://datatracker.ietf.org/doc/html/rfc7591) (OAuth 2.0 Dynamic Client Registration Protocol).
     * @type {string}
     * @memberof ClientRegistrationUpdateRequest
     */
    json: string;
}
