// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.2.30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ClientRegistrationGetRequest
 */
export interface ClientRegistrationGetRequest {
    /**
     * Client ID. 
     * @type {string}
     * @memberof ClientRegistrationGetRequest
     */
    clientId: string;
    /**
     * Client registration access token.
     * @type {string}
     * @memberof ClientRegistrationGetRequest
     */
    token: string;
}
