// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ClientAuthorizationGetListResponse
 */
export interface ClientAuthorizationGetListResponse {
    /**
     * Start index of search results (inclusive). 
     * @type {number}
     * @memberof ClientAuthorizationGetListResponse
     */
    start?: number;
    /**
     * End index of search results (exclusive). 
     * @type {number}
     * @memberof ClientAuthorizationGetListResponse
     */
    end?: number;
    /**
     * Unique ID of a client developer. 
     * @type {string}
     * @memberof ClientAuthorizationGetListResponse
     */
    developer?: string;
    /**
     * Unique user ID of an end-user. 
     * @type {string}
     * @memberof ClientAuthorizationGetListResponse
     */
    subject?: string;
    /**
     * Unique ID of a client developer. 
     * @type {number}
     * @memberof ClientAuthorizationGetListResponse
     */
    totalCount?: number;
    /**
     * An array of clients. 
     * @type {Array<object>}
     * @memberof ClientAuthorizationGetListResponse
     */
    clients?: Array<object>;
}
