// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.2.30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface DeviceAuthorizationRequest
 */
export interface DeviceAuthorizationRequest {
    /**
     * Parameters of a device authorization request which are the request parameters that the device authorization endpoint of the authorization server implementation received from the client application.  The value of `parameters` is the entire entity body (which is formatted in `application/x-www-form-urlencoded`) of the request from the client application. 
     * @type {string}
     * @memberof DeviceAuthorizationRequest
     */
    parameters: string;
    /**
     * The client ID extracted from Authorization header of the device authorization request from the client application.  If the device authorization endpoint of the authorization server implementation supports Basic `Authentication` as a means of client authentication, and the request from the client application contained its client ID in `Authorization` header, the value should be extracted and set to this parameter. 
     * @type {string}
     * @memberof DeviceAuthorizationRequest
     */
    clientId?: string;
    /**
     * The client secret extracted from `Authorization` header of the device authorization request from the client application.  If the device authorization endpoint of the authorization server implementation supports Basic Authentication as a means of client authentication, and the request from the client application contained its client secret in `Authorization` header, the value should be extracted and set to this parameter. 
     * @type {string}
     * @memberof DeviceAuthorizationRequest
     */
    clientSecret?: string;
    /**
     * The client certificate used in the TLS connection between the client application and the device authorization endpoint of the authorization server. 
     * @type {string}
     * @memberof DeviceAuthorizationRequest
     */
    clientCertificate?: string;
    /**
     * The client certificate path presented by the client during client authentication. Each element is a string in PEM format.
     * @type {string}
     * @memberof DeviceAuthorizationRequest
     */
    clientCertificatePath?: string;
}
