// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.2.30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface DeviceVerificationRequest
 */
export interface DeviceVerificationRequest {
    /**
     * A user code.
     * @type {string}
     * @memberof DeviceVerificationRequest
     */
    userCode: string;
}
