// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface FederationConfigurationResponse
 */
export interface FederationConfigurationResponse {
    /**
     * The code which represents the result of the API call.
     * @type {string}
     * @memberof FederationConfigurationResponse
     */
    resultCode?: string;
    /**
     * A short message which explains the result of the API call.
     * @type {string}
     * @memberof FederationConfigurationResponse
     */
    resultMessage?: string;
    /**
     * The next action that the authorization server implementation should take.
     * @type {string}
     * @memberof FederationConfigurationResponse
     */
    action?: FederationConfigurationResponseActionEnum;
    /**
     * The content that the authorization server implementation is to return to the client application. Its format varies depending on the value of `action` parameter. 
     * @type {string}
     * @memberof FederationConfigurationResponse
     */
    responseContent?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum FederationConfigurationResponseActionEnum {
    Ok = 'OK',
    NotFound = 'NOT_FOUND',
    InternalServerError = 'INTERNAL_SERVER_ERROR'
}

