// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface GMResponse
 */
export interface GMResponse {
    /**
     * The code which represents the result of the API call.
     * @type {string}
     * @memberof GMResponse
     */
    resultCode?: string;
    /**
     * A short message which explains the result of the API call.
     * @type {string}
     * @memberof GMResponse
     */
    resultMessage?: string;
    /**
     * The next action that the authorization server implementation should take.
     * @type {string}
     * @memberof GMResponse
     */
    action?: GMResponseActionEnum;
    /**
     * The content that the authorization server implementation is to return to the client application. Its format varies depending on the value of `action` parameter. 
     * @type {string}
     * @memberof GMResponse
     */
    responseContent?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum GMResponseActionEnum {
    Ok = 'OK',
    NoContent = 'NO_CONTENT',
    Unauthorized = 'UNAUTHORIZED',
    Forbidden = 'FORBIDDEN',
    NotFound = 'NOT_FOUND',
    CallerError = 'CALLER_ERROR',
    AuthleteError = 'AUTHLETE_ERROR'
}

