// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The grant management action of the device authorization request.  The `grant_management_action` request parameter is defined in [Grant Management for OAuth 2.0](https://openid.net/specs/fapi-grant-management.html). 
 * @export
 * @enum {string}
 */
export enum GrantManagementAction {
    Create = 'CREATE',
    Query = 'QUERY',
    Replace = 'REPLACE',
    Revoke = 'REVOKE',
    Merge = 'MERGE'
}

