// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface GrantScope
 */
export interface GrantScope {
    /**
     * Space-delimited scopes. 
     * @type {string}
     * @memberof GrantScope
     */
    scope?: string;
    /**
     * List of resource indicators. 
     * @type {Array<string>}
     * @memberof GrantScope
     */
    resource?: Array<string>;
}
