// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Holds information about a key managed in an HSM (Hardware Security Module) 
 * @export
 * @interface Hsk
 */
export interface Hsk {
    /**
     * The key type (EC or RSA) 
     * @type {string}
     * @memberof Hsk
     */
    kty?: string;
    /**
     * Get the use of the key on the HSM. When the key use is \"sig\" (signature), the private key on the HSM is used to sign data and the corresponding public key is used to verify the signature. When the key use is \"enc\" (encryption), the private key on the HSM is used to decrypt encrypted data which have been encrypted with the corresponding public key 
     * @type {string}
     * @memberof Hsk
     */
    use?: string;
    /**
     * Key ID for the key on the HSM. 
     * @type {string}
     * @memberof Hsk
     */
    kid?: string;
    /**
     * The name of the HSM. The identifier for the HSM that sits behind the Authlete server. For example, \"google\". 
     * @type {string}
     * @memberof Hsk
     */
    hsmName?: string;
    /**
     * The handle for the key on the HSM. A handle is a base64url-encoded 256-bit random value (43 letters) which is assigned by Authlete on the call of the /api/hsk/create API 
     * @type {string}
     * @memberof Hsk
     */
    handle?: string;
    /**
     * The public key that corresponds to the key on the HSM.
     * @type {string}
     * @memberof Hsk
     */
    publicKey?: string;
}
