// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    Hsk,
} from './';

/**
 * @export
 * @interface HskGetListResponse
 */
export interface HskGetListResponse {
    /**
     * The code which represents the result of the API call.
     * @type {string}
     * @memberof HskGetListResponse
     */
    resultCode?: string;
    /**
     * A short message which explains the result of the API call.
     * @type {string}
     * @memberof HskGetListResponse
     */
    resultMessage?: string;
    /**
     * Result of the API call
     * @type {string}
     * @memberof HskGetListResponse
     */
    action?: HskGetListResponseActionEnum;
    /**
     * List of HSK
     * @type {Array<Hsk>}
     * @memberof HskGetListResponse
     */
    hsks?: Array<Hsk>;
}

/**
 * @export
 * @enum {string}
 */
export enum HskGetListResponseActionEnum {
    Success = 'SUCCESS',
    InvalidRequest = 'INVALID_REQUEST',
    ServerError = 'SERVER_ERROR'
}

