// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.2.30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface JoseVerifyResponse
 */
export interface JoseVerifyResponse {
    /**
     * The code which represents the result of the API call.
     * @type {string}
     * @memberof JoseVerifyResponse
     */
    resultCode?: string;
    /**
     * A short message which explains the result of the API call.
     * @type {string}
     * @memberof JoseVerifyResponse
     */
    resultMessage?: string;
    /**
     * The result of the verification on the JOSE object. 
     * @type {boolean}
     * @memberof JoseVerifyResponse
     */
    valid?: boolean;
    /**
     * The result of the signature verification. 
     * @type {boolean}
     * @memberof JoseVerifyResponse
     */
    signatureValid?: boolean;
    /**
     * The list of missing claims. 
     * @type {Array<string>}
     * @memberof JoseVerifyResponse
     */
    missingClaims?: Array<string>;
    /**
     * The list of invalid claims. 
     * @type {Array<string>}
     * @memberof JoseVerifyResponse
     */
    invalidClaims?: Array<string>;
    /**
     * The list of error messages. 
     * @type {Array<string>}
     * @memberof JoseVerifyResponse
     */
    errorDescriptions?: Array<string>;
}
