// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Pair
 */
export interface Pair {
    /**
     * The key part.
     * @type {string}
     * @memberof Pair
     */
    key?: string;
    /**
     * The value part.
     * @type {string}
     * @memberof Pair
     */
    value?: string;
}
