// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.2.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The prompt that the UI displayed to the end-user must satisfy as the minimum level. This value comes from `prompt` request parameter.  When the authorization request does not contain `prompt` request parameter, `CONSENT` is used as the default value.  See \"[OpenID Connect Core 1.0, 3.1.2.1. Authentication Request](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest), prompt\" for `prompt` request parameter. 
 * @export
 * @enum {string}
 */
export enum Prompt {
    None = 'NONE',
    Login = 'LOGIN',
    Consent = 'CONSENT',
    SelectAccount = 'SELECT_ACCOUNT'
}

