// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.2.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface PushedAuthReqRequest
 */
export interface PushedAuthReqRequest {
    /**
     * The pushed authorization request body received from the client application.  The value of parameters is the entire entity body (which is formatted in `application/x-www-form-urlencoded`) of the request from the client application. 
     * @type {string}
     * @memberof PushedAuthReqRequest
     */
    parameters: string;
    /**
     * The client ID extracted from `Authorization` header of the pushed request from the client application. 
     * @type {string}
     * @memberof PushedAuthReqRequest
     */
    clientId?: string;
    /**
     * The client secret extracted from `Authorization` header of the pushed authorization request from the client application. 
     * @type {string}
     * @memberof PushedAuthReqRequest
     */
    clientSecret?: string;
    /**
     * The client certificate from the MTLS connection to pushed authorization endpoint from the client application.
     * @type {string}
     * @memberof PushedAuthReqRequest
     */
    clientCertificate?: string;
    /**
     * The certificate path presented by the client during client authentication. These certificates are strings in PEM format. 
     * @type {string}
     * @memberof PushedAuthReqRequest
     */
    clientCertificatePath?: string;
}
