// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.2.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ResponseType {
    None = 'NONE',
    Code = 'CODE',
    Token = 'TOKEN',
    IdToken = 'ID_TOKEN',
    CodeToken = 'CODE_TOKEN',
    CodeIdToken = 'CODE_ID_TOKEN',
    IdTokenToken = 'ID_TOKEN_TOKEN',
    CodeIdTokenToken = 'CODE_ID_TOKEN_TOKEN'
}

