// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.2.30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface RevocationResponse
 */
export interface RevocationResponse {
    /**
     * The code which represents the result of the API call.
     * @type {string}
     * @memberof RevocationResponse
     */
    resultCode?: string;
    /**
     * A short message which explains the result of the API call.
     * @type {string}
     * @memberof RevocationResponse
     */
    resultMessage?: string;
    /**
     * The next action that the authorization server implementation should take.
     * @type {string}
     * @memberof RevocationResponse
     */
    action?: RevocationResponseActionEnum;
    /**
     * The content that the authorization server implementation is to return to the client application. Its format varies depending on the value of `action` parameter. 
     * @type {string}
     * @memberof RevocationResponse
     */
    responseContent?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum RevocationResponseActionEnum {
    InternalServerError = 'INTERNAL_SERVER_ERROR',
    InvalidClient = 'INVALID_CLIENT',
    BadRequest = 'BAD_REQUEST',
    Ok = 'OK'
}

