// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.2.30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface StandardIntrospectionRequest
 */
export interface StandardIntrospectionRequest {
    /**
     * Request parameters which comply with the introspection request defined in \"[2.1. Introspection Request](https://datatracker.ietf.org/doc/html/rfc7662#section-2.1)\" in RFC 7662.  The implementation of the introspection endpoint of your authorization server will receive an HTTP POST [[RFC 7231](https://datatracker.ietf.org/doc/html/rfc7231)] request with parameters in the `application/x-www-form-urlencoded` format. It is the entity body of the request that Authlete\'s  `/api/auth/introspection/standard` API expects as the value of `parameters`. 
     * @type {string}
     * @memberof StandardIntrospectionRequest
     */
    parameters: string;
    /**
     * Flag indicating whether to include hidden properties in the output.  Authlete has a mechanism whereby to associate arbitrary key-value pairs with an access token. Each key-value pair has a hidden attribute. By default, key-value pairs whose hidden attribute is set to `true` are not embedded in the standard introspection output.  If the `withHiddenProperties` request parameter is given and its value is `true`, `/api/auth/introspection/standard API includes all the associated key-value pairs into the output regardless of the value of the hidden attribute.
     * @type {string}
     * @memberof StandardIntrospectionRequest
     */
    withHiddenProperties?: string;
}
