// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.2.30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface TaggedValue
 */
export interface TaggedValue {
    /**
     * The language tag part.
     * @type {string}
     * @memberof TaggedValue
     */
    tag?: string;
    /**
     * The value part.
     * @type {string}
     * @memberof TaggedValue
     */
    value?: string;
}
