// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    AuthorizationDetailsElement,
    Property,
} from './';

/**
 * @export
 * @interface TokenInfo
 */
export interface TokenInfo {
    /**
     * The client id.
     * @type {number}
     * @memberof TokenInfo
     */
    clientId?: number;
    /**
     * The alias of the client.
     * @type {string}
     * @memberof TokenInfo
     */
    clientIdAlias?: string;
    /**
     * Flag specifying if the alias was used to identify the client
     * @type {boolean}
     * @memberof TokenInfo
     */
    clientIdAliasUsed?: boolean;
    /**
     * the resource owner unique id
     * @type {string}
     * @memberof TokenInfo
     */
    subject?: string;
    /**
     * The scopes granted on the token
     * @type {Array<string>}
     * @memberof TokenInfo
     */
    scopes?: Array<string>;
    /**
     * time which the token expires.
     * @type {number}
     * @memberof TokenInfo
     */
    expiresAt?: number;
    /**
     * Extra properties associated with the token
     * @type {Array<Property>}
     * @memberof TokenInfo
     */
    properties?: Array<Property>;
    /**
     * The array of the resources of the token.
     * @type {Array<string>}
     * @memberof TokenInfo
     */
    resources?: Array<string>;
    /**
     * @type {AuthorizationDetailsElement}
     * @memberof TokenInfo
     */
    authorizationDetails?: AuthorizationDetailsElement;
    /**
     * The entity ID of the client. 
     * @type {string}
     * @memberof TokenInfo
     */
    clientEntityId?: string;
    /**
     * Flag which indicates whether the entity ID of the client was used when the request for the access token was made.
     * @type {boolean}
     * @memberof TokenInfo
     */
    clientEntityIdUsed?: boolean;
}
