// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    AuthorizationDetails,
    Property,
} from './';

/**
 * @export
 * @interface TokenCreateResponse
 */
export interface TokenCreateResponse {
    /**
     * The code which represents the result of the API call.
     * @type {string}
     * @memberof TokenCreateResponse
     */
    resultCode?: string;
    /**
     * A short message which explains the result of the API call.
     * @type {string}
     * @memberof TokenCreateResponse
     */
    resultMessage?: string;
    /**
     * The next action that the authorization server implementation should take.
     * @type {string}
     * @memberof TokenCreateResponse
     */
    action?: TokenCreateResponseActionEnum;
    /**
     * The newly issued access token.
     * @type {string}
     * @memberof TokenCreateResponse
     */
    accessToken?: string;
    /**
     * The ID of the client application associated with the access token. 
     * @type {number}
     * @memberof TokenCreateResponse
     */
    clientId?: number;
    /**
     * The time at which the access token expires. 
     * @type {number}
     * @memberof TokenCreateResponse
     */
    expiresAt?: number;
    /**
     * The duration of the newly issued access token in seconds. 
     * @type {number}
     * @memberof TokenCreateResponse
     */
    expiresIn?: number;
    /**
     * The grant type for the newly issued access token. 
     * @type {string}
     * @memberof TokenCreateResponse
     */
    grantType?: string;
    /**
     * The extra properties associated with the access token. 
     * @type {Array<Property>}
     * @memberof TokenCreateResponse
     */
    properties?: Array<Property>;
    /**
     * The newly issued refresh token. 
     * @type {string}
     * @memberof TokenCreateResponse
     */
    refreshToken?: string;
    /**
     * Scopes which are associated with the access token. 
     * @type {Array<string>}
     * @memberof TokenCreateResponse
     */
    scopes?: Array<string>;
    /**
     * The subject (= unique identifier) of the user associated with the newly issued access token. 
     * @type {string}
     * @memberof TokenCreateResponse
     */
    subject?: string;
    /**
     * The token type of the access token. 
     * @type {string}
     * @memberof TokenCreateResponse
     */
    tokenType?: string;
    /**
     * If the authorization server is configured to issue JWT-based access tokens (= if `Service.accessTokenSignAlg` is set to a `non-null` value), a JWT-based access token is issued along with the original random-string one. 
     * @type {string}
     * @memberof TokenCreateResponse
     */
    jwtAccessToken?: string;
    /**
     * @type {AuthorizationDetails}
     * @memberof TokenCreateResponse
     */
    authorizationDetails?: AuthorizationDetails;
    /**
     * the flag which indicates whether the access token is for an external attachment. 
     * @type {boolean}
     * @memberof TokenCreateResponse
     */
    forExternalAttachment?: boolean;
}

/**
 * @export
 * @enum {string}
 */
export enum TokenCreateResponseActionEnum {
    InternalServerError = 'INTERNAL_SERVER_ERROR',
    BadRequest = 'BAD_REQUEST',
    Forbidden = 'FORBIDDEN',
    Ok = 'OK'
}

