// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.2.30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface TokenRevokeRequest
 */
export interface TokenRevokeRequest {
    /**
     * The identifier of an access token to revoke. 
     * @type {string}
     * @memberof TokenRevokeRequest
     */
    accessTokenIdentifier?: string;
    /**
     * The identifier of a client. 
     * @type {string}
     * @memberof TokenRevokeRequest
     */
    clientIdentifier?: string;
    /**
     * The identifier of a refresh token to revoke. 
     * @type {string}
     * @memberof TokenRevokeRequest
     */
    refreshTokenIdentifier?: string;
    /**
     * The subject of a resource owner.
     * @type {string}
     * @memberof TokenRevokeRequest
     */
    subject?: string;
}
