// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.2.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface UserinfoIssueRequest
 */
export interface UserinfoIssueRequest {
    /**
     * The access token that has been passed to the userinfo endpoint by the client application. In other words, the access token which was contained in the userinfo request. 
     * @type {string}
     * @memberof UserinfoIssueRequest
     */
    token: string;
    /**
     * Claims in JSON format. As for the format, see [OpenID Connect Core 1.0, 5.1. Standard Claims](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims). 
     * @type {string}
     * @memberof UserinfoIssueRequest
     */
    claims?: string;
    /**
     * The value of the `sub` claim. If the value of this request parameter is not empty, it is used as the value of the `sub` claim. Otherwise, the value of the subject associated with the access token is used.
     * @type {string}
     * @memberof UserinfoIssueRequest
     */
    sub?: string;
}
