// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface UserinfoIssueResponse
 */
export interface UserinfoIssueResponse {
    /**
     * The code which represents the result of the API call.
     * @type {string}
     * @memberof UserinfoIssueResponse
     */
    resultCode?: string;
    /**
     * A short message which explains the result of the API call.
     * @type {string}
     * @memberof UserinfoIssueResponse
     */
    resultMessage?: string;
    /**
     * The next action that the authorization server implementation should take.
     * @type {string}
     * @memberof UserinfoIssueResponse
     */
    action?: UserinfoIssueResponseActionEnum;
    /**
     * The content that the authorization server implementation can use as the value of `WWW-Authenticate` header on errors. 
     * @type {string}
     * @memberof UserinfoIssueResponse
     */
    responseContent?: string;
    /**
     * The signature header of the response message. 
     * @type {string}
     * @memberof UserinfoIssueResponse
     */
    signature?: string;
    /**
     * The signature-input header of the response message 
     * @type {string}
     * @memberof UserinfoIssueResponse
     */
    signatureInput?: string;
    /**
     * The content-digest header of the response message 
     * @type {string}
     * @memberof UserinfoIssueResponse
     */
    contentDigest?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum UserinfoIssueResponseActionEnum {
    InternalServerError = 'INTERNAL_SERVER_ERROR',
    BadRequest = 'BAD_REQUEST',
    Unauthorized = 'UNAUTHORIZED',
    Forbidden = 'FORBIDDEN',
    Json = 'JSON',
    Ok = 'OK'
}

