// tslint:disable
/**
 * Authlete API
 * Authlete API Document. 
 *
 * The version of the OpenAPI document: 2.2.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The character set for end-user verification codes (`user_code`) for Device Flow. 
 * @export
 * @enum {string}
 */
export enum UserCodeCharset {
    Base20 = 'BASE20',
    Numeric = 'NUMERIC'
}

